name: Update Snake Animation

on:
  push:
    branches:
      - main  # Ou a branch que você deseja usar

jobs:
  update-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Snake Animation
        run: |
          curl -o snake.svg https://raw.githubusercontent.com/Bianca-leal/Bianca-leal/output/github-contribution-grid-snake.svg
          mv snake.svg images/snake.svg

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add images/snake.svg
          git commit -m "Update Snake Animation [skip ci]"
          git push

